import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Export assessment to PDF
export const exportAssessmentToPDF = (assessment) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.text('TherapEase Assessment Report', 105, 20, { align: 'center' });
  
  // Assessment Details
  doc.setFontSize(14);
  doc.text('Assessment Information', 20, 40);
  
  doc.setFontSize(10);
  doc.text(`Patient: ${assessment.patientName}`, 20, 55);
  doc.text(`Assessment: ${assessment.title}`, 20, 65);
  doc.text(`Type: ${assessment.type}`, 20, 75);
  doc.text(`Category: ${assessment.category}`, 20, 85);
  doc.text(`Date: ${assessment.date}`, 20, 95);
  doc.text(`Status: ${assessment.status}`, 20, 105);
  
  if (assessment.score !== null) {
    doc.text(`Score: ${assessment.score}/${assessment.maxScore}`, 20, 115);
  }
  
  // Assessment Areas Table
  if (assessment.areas && assessment.areas.length > 0) {
    doc.setFontSize(14);
    doc.text('Assessment Areas', 20, 140);
    
    const areasData = assessment.areas.map(area => [
      area.name,
      area.score || 'N/A',
      area.maxScore,
      area.score ? `${Math.round((area.score / area.maxScore) * 100)}%` : 'N/A'
    ]);
    
    doc.autoTable({
      startY: 150,
      head: [['Area', 'Score', 'Max Score', 'Percentage']],
      body: areasData,
      theme: 'grid',
      headStyles: { fillColor: [34, 197, 94] }
    });
  }
  
  // Summary
  if (assessment.summary) {
    doc.setFontSize(14);
    doc.text('Summary', 20, doc.lastAutoTable.finalY + 20);
    
    doc.setFontSize(10);
    const splitSummary = doc.splitTextToSize(assessment.summary, 170);
    doc.text(splitSummary, 20, doc.lastAutoTable.finalY + 35);
  }
  
  // Recommendations
  if (assessment.recommendations && assessment.recommendations.length > 0) {
    doc.setFontSize(14);
    doc.text('Recommendations', 20, doc.lastAutoTable.finalY + 60);
    
    doc.setFontSize(10);
    assessment.recommendations.forEach((rec, index) => {
      const yPos = doc.lastAutoTable.finalY + 75 + (index * 10);
      doc.text(`• ${rec}`, 25, yPos);
    });
  }
  
  // AI Insights
  if (assessment.aiInsights) {
    doc.setFontSize(14);
    doc.text('AI Insights', 20, doc.lastAutoTable.finalY + 100);
    
    doc.setFontSize(10);
    const splitInsights = doc.splitTextToSize(assessment.aiInsights, 170);
    doc.text(splitInsights, 20, doc.lastAutoTable.finalY + 115);
  }
  
  // Footer
  doc.setFontSize(8);
  doc.text(`Generated on ${new Date().toLocaleDateString()} by TherapEase`, 105, doc.internal.pageSize.height - 10, { align: 'center' });
  
  // Save the PDF
  doc.save(`assessment-${assessment.patientName.replace(/\s+/g, '-')}-${assessment.date}.pdf`);
};

// Export assessment to CSV
export const exportAssessmentToCSV = (assessment) => {
  const csvContent = [
    ['Assessment Report'],
    [''],
    ['Patient', assessment.patientName],
    ['Assessment', assessment.title],
    ['Type', assessment.type],
    ['Category', assessment.category],
    ['Date', assessment.date],
    ['Status', assessment.status],
    ['Score', assessment.score !== null ? `${assessment.score}/${assessment.maxScore}` : 'N/A'],
    [''],
    ['Assessment Areas'],
    ['Area Name', 'Score', 'Max Score', 'Percentage']
  ];
  
  if (assessment.areas && assessment.areas.length > 0) {
    assessment.areas.forEach(area => {
      const percentage = area.score ? Math.round((area.score / area.maxScore) * 100) : 'N/A';
      csvContent.push([area.name, area.score || 'N/A', area.maxScore, percentage]);
    });
  }
  
  csvContent.push(['']);
  csvContent.push(['Summary']);
  csvContent.push([assessment.summary || 'N/A']);
  
  if (assessment.recommendations && assessment.recommendations.length > 0) {
    csvContent.push(['']);
    csvContent.push(['Recommendations']);
    assessment.recommendations.forEach(rec => {
      csvContent.push([rec]);
    });
  }
  
  if (assessment.aiInsights) {
    csvContent.push(['']);
    csvContent.push(['AI Insights']);
    csvContent.push([assessment.aiInsights]);
  }
  
  csvContent.push(['']);
  csvContent.push(['Generated on', new Date().toLocaleDateString()]);
  csvContent.push(['Generated by', 'TherapEase']);
  
  const csvString = csvContent.map(row => row.map(cell => `"${cell}"`).join(',')).join('\n');
  const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `assessment-${assessment.patientName.replace(/\s+/g, '-')}-${assessment.date}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
};

// Export multiple assessments to CSV
export const exportMultipleAssessmentsToCSV = (assessments) => {
  const csvContent = [
    ['Multiple Assessments Report'],
    [''],
    ['Patient', 'Assessment', 'Type', 'Category', 'Date', 'Status', 'Score', 'Summary']
  ];
  
  assessments.forEach(assessment => {
    csvContent.push([
      assessment.patientName,
      assessment.title,
      assessment.type,
      assessment.category,
      assessment.date,
      assessment.status,
      assessment.score !== null ? `${assessment.score}/${assessment.maxScore}` : 'N/A',
      assessment.summary || 'N/A'
    ]);
  });
  
  csvContent.push(['']);
  csvContent.push(['Generated on', new Date().toLocaleDateString()]);
  csvContent.push(['Generated by', 'TherapEase']);
  
  const csvString = csvContent.map(row => row.map(cell => `"${cell}"`).join(',')).join('\n');
  const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `multiple-assessments-${new Date().toISOString().split('T')[0]}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
};

// Export assessment summary to PDF
export const exportAssessmentSummaryToPDF = (assessments, filters = {}) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.text('TherapEase Assessment Summary Report', 105, 20, { align: 'center' });
  
  // Filters applied
  if (Object.keys(filters).length > 0) {
    doc.setFontSize(12);
    doc.text('Filters Applied:', 20, 35);
    
    doc.setFontSize(10);
    let yPos = 45;
    Object.entries(filters).forEach(([key, value]) => {
      if (value) {
        doc.text(`${key}: ${value}`, 25, yPos);
        yPos += 8;
      }
    });
  }
  
  // Summary statistics
  doc.setFontSize(14);
  doc.text('Summary Statistics', 20, 70);
  
  doc.setFontSize(10);
  const totalAssessments = assessments.length;
  const completedAssessments = assessments.filter(a => a.status === 'completed').length;
  const scheduledAssessments = assessments.filter(a => a.status === 'scheduled').length;
  const avgScore = completedAssessments > 0 
    ? Math.round(assessments.filter(a => a.status === 'completed').reduce((sum, a) => sum + (a.score || 0), 0) / completedAssessments)
    : 'N/A';
  
  doc.text(`Total Assessments: ${totalAssessments}`, 20, 85);
  doc.text(`Completed: ${completedAssessments}`, 20, 95);
  doc.text(`Scheduled: ${scheduledAssessments}`, 20, 105);
  doc.text(`Average Score: ${avgScore}`, 20, 115);
  
  // Assessments table
  doc.setFontSize(14);
  doc.text('Assessment Details', 20, 140);
  
  const tableData = assessments.map(assessment => [
    assessment.patientName,
    assessment.title,
    assessment.type,
    assessment.category,
    assessment.date,
    assessment.status,
    assessment.score !== null ? `${assessment.score}/${assessment.maxScore}` : 'N/A'
  ]);
  
  doc.autoTable({
    startY: 150,
    head: [['Patient', 'Assessment', 'Type', 'Category', 'Date', 'Status', 'Score']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [34, 197, 94] },
    styles: { fontSize: 8 }
  });
  
  // Footer
  doc.setFontSize(8);
  doc.text(`Generated on ${new Date().toLocaleDateString()} by TherapEase`, 105, doc.internal.pageSize.height - 10, { align: 'center' });
  
  // Save the PDF
  doc.save(`assessment-summary-${new Date().toISOString().split('T')[0]}.pdf`);
};

